### ISSUE TITLE
postcss-px-to-viewport-8-plugin@1.2.5版本，animation中的px单位不会转换

### ISSUE THREAD

**Issue by Cacivy** [lkxian888/postcss-px-to-viewport-8-plugin#36]
见标题，降级到@1.2.3版本后正常

**Comment by Cacivy** [comment]
```css
@keyframes showLine {
  0% {
    width: 10px;
  }

  100% {
    width: 144px;
  }
}
```
